export default {
    yutovo_caption: 'Ютово',

    'Ok': 'Ok',
    'Unknown command': 'Неизвестная команда',
    'Json error': 'Ошибка JSON',
    'No field': 'Нет поля',
    'Field error': 'Ошибка поля',
    'Solver error': 'Ошибка решателя',
    'Parser error': 'Ошибка разбора',
    'Operation error': 'Ошибочная операция',
    'Solver restarted': 'Рестарт сервера',
    'Syntax error': 'Синтаксическая ошибка',
    'Wrong arguments count': 'Неправильное количество аргументов',
    'Unknown identifier': 'Неизвестный идентификатор',
    'Expression expected': 'Ожидается выражение',
    'Division by zero': 'Деление на ноль',
    'Overflow': 'Переполнение',
    'Argument is over': 'Переполнение аргумента',
    'Units are incompatible': 'Размерности несовместимы',
    'Conversion does not fit': 'Преобразование невозможно',

    'Functions': 'Функции',
    'Variables': 'Переменные',
    'Units': 'Размерности',

    'SI': 'СИ',
    'rus': 'русская',

    'length': 'длина',
    'mass': 'масса',
    'time': 'время',
    'amount of matter': 'количество вещества',
    'electric current': 'электрический ток',
    'luminosity': 'светимость',
    'temperature': 'температура',
    'frequency': 'частота',
    'power': 'сила',
    'others': 'другие',

    'New document': 'Новый документ',
    'Upload document': 'Загрузить документ',
    'Save document': 'Сохранить документ',
    'Save document as': 'Сохранить документ как',
    'Download document': 'Скачать документ',
    'Rename document': 'Переименовать документ',
    'Delete document': 'Удалить документ',
    'Undo': 'Отменить',
    'Redo': 'Повторить',
    'Cut': 'Вырезать',
    'Copy': 'Скопировать',
    'Paste': 'Вставить',
    'Insert code': 'Вставить код',
    'Paragraph format': 'Формат параграфа',
    'Font family': 'Шрифт',
    'Font size': 'Размер шрифта',
    'Bold': 'Жирный',
    'Italic': 'Курсив',
    'Underline': 'Подчеркнутый',
    'Text color': 'Цвет текста',
    'Text background color': 'Цвет фона текста',

    'Plus': 'Плюс',
    'Minus': 'Минус',
    'Multiply': 'Умножение',
    'Division': 'Деление',
    'Power': 'Степень',
    'Square root': 'Квадратный корень',
    'Root of degree': 'Корень степени',
    'Subscript': 'Нижний регистр',
    'Fences': 'Скобки',
    'Radian': 'Радиан',
    'Degree': 'Градус',
    'Minute': 'Минута',
    'Second': 'Секунда',
    'Grad': 'Град',
    'Sum': 'Сумма',
    'Product': 'Произведение',
    'Assignment': 'Присваивание',
    'Unit': 'Размерность',
    'Equation': 'Равенство',
    'rad': 'рад',
    'grad': 'град',

    'Filter': 'Фильтр',

    'Documents': 'Документы',
    'Tasks': 'Задачи',
    'Identifiers': 'Идентификаторы'
};