export default {
    yutovo_caption: 'Ютово',

    'Ok': 'Ok',
    'Unknown command': 'Неизвестная команда',
    'Json error': 'Ошибка JSON',
    'No field': 'Нет поля',
    'Field error': 'Ошибка поля',
    'Solver error': 'Ошибка решателя',
    'Parser error': 'Ошибка разбора',
    'Operation error': 'Ошибочная операция',
    'Solver restarted': 'Рестарт сервера',
    'Syntax error': 'Синтаксическая ошибка',
    'Wrong arguments count': 'Неправильное количество аргументов',
    'Unknown identifier': 'Неизвестный идентификатор',
    'Expression expected': 'Ожидается выражение',
    'Division by zero': 'Деление на ноль',
    'Overflow': 'Переполнение',
    'Argument is over': 'Переполнение аргумента',
    'Units are incompatible': 'Размерности несовместимы',
    'Conversion does not fit': 'Преобразование невозможно',

    'Builtin functions': 'Встроенные функции',
    'User functions': 'Пользовательские функции',
    'Builtin variables': 'Встроенные переменные',
    'User variables': 'Пользовательские переменные',
    'Builtin units': 'Встроенные размерности',
    'User units': 'Пользовательские размерности',

    'New document': 'Новый документ',
    'Open document': 'Открыть документ',
    'Save document': 'Сохранить документ',
    'Save document as': 'Сохранить документ как',
    'Rename document': 'Переименовать документ',
    'Delete document': 'Удалить документ',
    'Undo': 'Отменить',
    'Redo': 'Повторить',
    'Cut': 'Вырезать',
    'Copy': 'Скопировать',
    'Paste': 'Вставить',
    'Insert code': 'Вставить код',
    'Paragraph format': 'Формат параграфа',
    'Font family': 'Шрифт',
    'Font size': 'Размер шрифта',
    'Bold': 'Жирный',
    'Italic': 'Курсив',
    'Underline': 'Подчеркнутый',
    'Text color': 'Цвет текста',
    'Text background color': 'Цвет фона текста',

    'Plus': 'Плюс',
    'Minus': 'Минус',
    'Multiply': 'Умножение',
    'Division': 'Деление',
    'Power': 'Степень',
    'Square root': 'Квадратный корень',
    'Root of degree': 'Корень степени',
    'Subscript': 'Нижний регистр',
    'Fences': 'Скобки',
    'Assignment': 'Присваивание',
    'Equation': 'Равенство'
};